param([Parameter(Mandatory)][string]$Source, [Parameter(Mandatory)][string]$Output)
$ErrorActionPreference = 'Stop'
$inv = [Globalization.CultureInfo]::InvariantCulture
$root = Get-Content -LiteralPath $Source -Raw -Encoding UTF8 | ConvertFrom-Json
$colors = @{}
$sb = New-Object Text.StringBuilder

function Pascal([string]$key) { (($key -split '[-.]') | Where-Object { $_ } | ForEach-Object { $_.Substring(0,1).ToUpperInvariant() + $_.Substring(1) }) -join '' }
function Rgb([string]$hex) { @([Convert]::ToInt32($hex.Substring(1,2),16), [Convert]::ToInt32($hex.Substring(3,2),16), [Convert]::ToInt32($hex.Substring(5,2),16)) }
function ToHex($c) { '#' + (($c | ForEach-Object { ([int]$_).ToString('X2', $inv) }) -join '') }
function ColorRef([string]$hex) { $c = Rgb $hex; '0x' + (($c[2] -shl 16) -bor ($c[1] -shl 8) -bor $c[0]).ToString('X6', $inv) }
function Over([string]$fg, [int]$alpha, [string]$bg) { $f = Rgb $fg; $b = Rgb $bg; ToHex (0..2 | ForEach-Object { [int][Math]::Round($b[$_] + ($f[$_] - $b[$_]) * $alpha / 255.0) }) }
function AlphaByte([double]$a) { [int][Math]::Round($a * 255) }
function Line([string]$s) { [void]$sb.AppendLine($s) }
function Doc([string]$text) { Line ('    /// <summary>' + [Security.SecurityElement]::Escape($text) + '</summary>') }
function Esc([string]$s) { $s.Replace('\', '\\').Replace('"', '\"') }
function Props($o) { $o.PSObject.Properties | Where-Object { $_.Value -is [pscustomobject] } }

Line '// <auto-generated>teknesyum-ui/theme.tokens.json</auto-generated>'
Line 'namespace Runly.Core.Theme;'
Line ''
Line '/// <summary>Teknesyum tokens, generated at build time from <c>teknesyum-ui/theme.tokens.json</c>.</summary>'
Line 'public static class TeknesyumTokens'
Line '{'

foreach ($group in 'brand', 'role') {
    foreach ($p in Props $root.$group) {
        if ($null -eq $p.Value.value) { continue }
        $hex = ([string]$p.Value.value).ToUpperInvariant()
        $colors[$p.Name] = $hex
        $name = Pascal $p.Name
        Doc "$group.$($p.Name) $hex"
        Line "    public const string $name = `"$hex`";"
        Doc "$name as a Win32 COLORREF."
        Line "    public const uint ${name}Ref = $(ColorRef $hex);"
    }
}

foreach ($a in @(@('Bg','black'), @('Label','renk-1'), @('Danger','renk-2'), @('DangerText','renk-2-text'))) {
    Doc "$($a[0]) follows $($a[1])."
    Line "    public const string $($a[0]) = `"$($colors[$a[1]])`";"
    Doc "$($a[0]) as a Win32 COLORREF."
    Line "    public const uint $($a[0])Ref = $(ColorRef $colors[$a[1]]);"
}

foreach ($p in Props $root.role) {
    if ($null -eq $p.Value.ref -or $null -eq $p.Value.alpha -or $null -eq $p.Value.over) { continue }
    $hex = Over $colors[$p.Value.ref] (AlphaByte ([double]$p.Value.alpha)) $colors[$p.Value.over]
    $name = Pascal $p.Name
    Doc "role.$($p.Name): $($p.Value.ref) at $(([double]$p.Value.alpha).ToString($inv)) over $($p.Value.over), $hex"
    Line "    public const string $name = `"$hex`";"
    Doc "$name as a Win32 COLORREF."
    Line "    public const uint ${name}Ref = $(ColorRef $hex);"
}

foreach ($p in Props $root.derived) {
    $alpha = $p.Value.alpha
    if ($null -eq $alpha -or -not ($alpha -is [double] -or $alpha -is [int] -or $alpha -is [decimal])) { continue }
    Doc "derived.$($p.Name) alpha $(([double]$alpha).ToString($inv)) as a byte."
    Line "    public const int $(Pascal $p.Name)Alpha = $(AlphaByte $alpha);"
}

$tone = $root.derived.'tone-scale'
foreach ($s in $tone.steps) {
    Doc "Tone step $s percent as an alpha byte."
    Line "    public const int Tone${s}Alpha = $(AlphaByte ($s / 100.0));"
    foreach ($b in $tone.bases) {
        $hex = Over $colors[$b] (AlphaByte ($s / 100.0)) $colors['surface']
        $name = (Pascal $b) + "Tone$s"
        Doc "$b at $s percent composited over surface."
        Line "    public const string $name = `"$hex`";"
        Doc "$name as a Win32 COLORREF."
        Line "    public const uint ${name}Ref = $(ColorRef $hex);"
    }
}

Doc 'Selected row fill: renk-1 tone 30 over surface.'
Line '    public const string SelectedFill = Renk1Tone30;'
Doc 'Row hairline: renk-1 tone 10 over surface.'
Line '    public const string GridLine = Renk1Tone10;'

function Numbers([string]$group, [string]$prefix) {
    foreach ($p in Props $root.$group) {
        $v = $p.Value.value
        if ($null -eq $v) { $v = $p.Value.ms }
        if ($null -eq $v) { continue }
        $name = $prefix + (Pascal $p.Name)
        if ($v -is [string]) {
            Doc "$group.$($p.Name)"
            Line "    public const string $name = `"$(Esc $v)`";"
        } elseif ($v -is [bool]) {
            Doc "$group.$($p.Name)"
            Line "    public const bool $name = $(([string]$v).ToLowerInvariant());"
        } else {
            $d = [double]$v
            Doc "$group.$($p.Name)"
            if ($d -eq [Math]::Floor($d)) { Line "    public const int $name = $(([int]$d).ToString($inv));" }
            else { Line "    public const double $name = $($d.ToString('R', $inv));" }
        }
    }
}
Numbers 'size' ''
Numbers 'space' 'Space'
Numbers 'shape' 'Shape'
Numbers 'metric' ''
Numbers 'duration' 'Duration'
Numbers 'motion' 'Motion'

foreach ($f in Props $root.font) {
    if ($null -eq $f.Value.chain) { continue }
    Doc "font.$($f.Name) chain."
    $items = ($f.Value.chain | ForEach-Object { '"' + (Esc $_) + '"' }) -join ', '
    Line "    public static readonly string[] $(Pascal $f.Name)Chain = [$items];"
}

Line '}'
$text = $sb.ToString()
if (-not (Test-Path -LiteralPath $Output) -or [IO.File]::ReadAllText($Output) -ne $text) {
    [void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Output))
    [IO.File]::WriteAllText($Output, $text, (New-Object Text.UTF8Encoding $false))
}
